"""Add gamification tables

Revision ID: 6e40c7e179d7
Revises: 008
Create Date: 2026-01-18 23:35:47.458794

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e40c7e179d7'
down_revision: Union[str, None] = '008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # ### Gamification Tables ###
    if 'gamification_stats' not in tables:
        op.create_table('gamification_stats',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.Column('xp', sa.Integer(), nullable=True, default=0),
            sa.Column('level', sa.Integer(), nullable=True, default=1),
            sa.Column('streak', sa.Integer(), nullable=True, default=0),
            sa.Column('last_activity_date', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_gamification_stats_id'), 'gamification_stats', ['id'], unique=False)
        op.create_index(op.f('ix_gamification_stats_user_id'), 'gamification_stats', ['user_id'], unique=True)

    if 'achievements' not in tables:
        op.create_table('achievements',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(), nullable=True),
            sa.Column('description', sa.String(), nullable=True),
            sa.Column('icon', sa.String(), nullable=True),
            sa.Column('xp_reward', sa.Integer(), nullable=True),
            sa.Column('condition_type', sa.String(), nullable=True),
            sa.Column('condition_value', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('title')
        )
        op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)

    if 'user_achievements' not in tables:
        op.create_table('user_achievements',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.Column('achievement_id', sa.Integer(), nullable=True),
            sa.Column('unlocked_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)

    # ### Auto-generated cleanup commands (Aligning DB with Models) ###
    # Note: These are optional but good for consistency
    try:
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    except:
        pass # Index might already exist

    # ... (Skipping other minor auto-gen changes to reduce risk of conflict for partner)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_limit(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_gamification_stats_user_id'), table_name='gamification_stats')
    op.drop_index(op.f('ix_gamification_stats_id'), table_name='gamification_stats')
    op.drop_table('gamification_stats')
    # ### end Alembic commands ###
